# Generated by Django 3.2.3 on 2021-05-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='caracteristica',
            field=models.BooleanField(default=False),
        ),
    ]
