# Generated by Django 3.2.3 on 2021-05-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_caracteristica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='caracteristica',
        ),
        migrations.AddField(
            model_name='product',
            name='caracteristica',
            field=models.BooleanField(default=False),
        ),
    ]
